### ISSUE TITLE
Make UI better by adding proper login page and its css 

### ISSUE THREAD

**Issue by LakshmiSowmya04** [LakshmiSowmya04/GradLink#1]
As this project is built from scratch I would like to add more designed manner that will be compatible .There should be a email or username field .password entering field a  drop down to select colleges listed and an option to enter new college name

**Comment by mohitahlawat2001** [comment]
in this we only have to make frontend login page?

**Comment by Anikesh02** [comment]
@LakshmiSowmya04 I would like to work on this issue. Can you please assign it to me?

**Comment by Anikesh02** [comment]
Yeah sure

**Comment by mohitahlawat2001** [comment]
sure

**Comment by Snehalgupta-07** [comment]
Hi! I would also like to work on it can u please assign it to me?

**Comment by Sahil-Gupta584** [comment]
@LakshmiSowmya04 i would like handle authentication from frontend to backend  with clerk

**Comment by Sahil-Gupta584** [comment]
> > @LakshmiSowmya04 i would like handle authentication from frontend to backend  with clerk
> 
> There are some modifications yet to be done like adding OTP ... please create frontend so that there won't be any merge conflicts

Only frontend ? Is someone working on backend for authenication?

**Comment by Anikesh02** [comment]
@LakshmiSowmya04  I'm almost done with the frontend part (I will enhance it more over the period) for both signup and sign-in. If someone wants to work on the backend part based on this frontend then let me know so I can raise a PR.

![image](https://github.com/user-attachments/assets/d40de094-9137-4062-a2ee-d07de9de6c58)
![image](https://github.com/user-attachments/assets/46dc3e2a-7481-42ac-991e-772216067a05)

**Comment by Sahil-Gupta584** [comment]
> This is really a nice UI ....check if it working on browser size variations and raise. A PR for backend or add an issue for someone to add backend

actually i am already builded login ui just small task is remaining

**Comment by Anikesh02** [comment]
Done

**Comment by Anikesh02** [comment]
> > Done
> 
> @Anikesh02 can you also add OTP option when signing up?

Like you want signup page should have email, password, select college , otp fields right ?

**Comment by Anikesh02** [comment]
Ok sure. I'll make the changes

**Comment by Anikesh02** [comment]
Hey, @LakshmiSowmya04 I've made changes on the sign-up page for the OTP field. Kindly review the PR.
