### ISSUE TITLE
Addition of University Model

### ISSUE THREAD

**Issue by anmol420** [LakshmiSowmya04/GradLink#11]
"University" model which will be used to register the university/college so that each user can be afflicted to the university and the university also gets a home page with Some posts and chat options for alumns and the onboard students. 

This model could be linked with the user model which will help us in finding the university which is registered on the portal, which is better than user registering his/her own university.

**Comment by anmol420** [comment]
@LakshmiSowmya04 Moreover finding someone with the user-id provided my mongodb is quite frustrating, so why not add username in the User model which will make things easier.

**Comment by anmol420** [comment]
@LakshmiSowmya04 Like if you view any of the other alumini apps or sites, first the university has to register itself on the portal then only user can register his/her self under the college/university name, if this doesn't happens then anyone can write any university name (wheather true or false), hence leading to misinformation. And regarding same college people having the chat, again you need a university database for this as this website will support multiple university having a seperate chat section which is independent from the other University/College.

Thats why I suggested to add university schema and database for the above mentioned problem.

**Comment by anmol420** [comment]
Under University Schema -
- Name: String
- Year: Date time
- Description: String
- chat : chat (ref)
- post: post (ref)
- user: user (ref)

Now when the user will register themselves on our portal then he/her would get an option to choose his/her university from a drop-down list so that if the university as not been registered on our portal student will not allowed to enter and this way many universities will try registeration on the portal which is far better than the students writing the name of their university. Drop-down list will contain all the names of the university which will be under the university database, hence will result in better mangement.

**Comment by LakshmiSowmya04** [comment]
anmol i have mentioned in discord ...make a PR asap for this

**Comment by anmol420** [comment]
ok @LakshmiSowmya04 ! on it
