### ISSUE TITLE
Handling ,Incorrect credentials

### ISSUE THREAD

**Issue by Bharath-KumarReddy** [LakshmiSowmya04/GradLink#12]
currently , if  I entered wrong credentials , then also I am able to login or signup 

We need to handle it carefully , so that only authorized people are allowed 

We need to show to the user that u entered wrong credentials and also whether that email exists or not and then password matching as well between signup and login 

If user is already present and he again tries to sign up with same email , we need to handle these situations 

Kindly , assign this to me under hacktoberfest_2024 , I will handle these things

**Comment by Bharath-KumarReddy** [comment]
once please check

**Comment by NikhilMadukumar** [comment]
@LakshmiSowmya04 
The Discord invite seems to be expired or invalid. Could you please update it?
