### ISSUE TITLE
Add a signup page and do styling 

### ISSUE THREAD

**Issue by LakshmiSowmya04** [LakshmiSowmya04/GradLink#2]
There should be a sign up page and also an option to register on behalf of their college

**Comment by NausadAli** [comment]
Hey Do I have To Write Plane CSS Or can use any Framework?
Like Bootstrap or Tailwind?

**Comment by NausadAli** [comment]
Ok then assign me this on..
Under hactober
thank you.

**Comment by Snehalgupta-07** [comment]
> There should be a sign up page and also an option to register on behalf of their college
do we have to handle the backend as well

**Comment by Snehalgupta-07** [comment]
do we handle the backend as well

**Comment by QaisarMoin** [comment]
can you provide website link ? So, i can understand easily
