### ISSUE TITLE
Addition of All Contributors in Readme | Readme Updation 

### ISSUE THREAD

**Issue by shubhagarwal1** [LakshmiSowmya04/GradLink#37]
We can add a file in workflows to add the contributors automatically to readme which basically enhaces the repo visibility
Hey @LakshmiSowmya04 please assign this task to me

**Comment by anmol420** [comment]
@LakshmiSowmya04 can you add `hacktoberfest` label !?

**Comment by shubhagarwal1** [comment]
> @LakshmiSowmya04 can you add `hacktoberfest` label !?

yes, make auto labeler is a diffrent task i can raise pr for that, can i complete this task and then raise issue for auto labler

**Comment by LakshmiSowmya04** [comment]
its not displaying images...please look into it

**Comment by shubhagarwal1** [comment]
> its not displaying images...please look into it

SURE WILL SOLVE THIS TODAY
