### ISSUE TITLE
Implement OTP-Based Email Verification for User Sign-Up

### ISSUE THREAD

**Issue by aryamagarwal** [LakshmiSowmya04/GradLink#7]
To enhance security and ensure valid user registrations, implement OTP (One-Time Password) based email verification during the sign-up process. When a user registers, an OTP should be sent to their provided email address. The user must enter the OTP on the verification screen to complete the registration. This will prevent fraudulent sign-ups, ensure valid email addresses, and improve overall platform security. The system should handle OTP generation, email delivery, and validation. Additionally, resend OTP and expiration functionality should be included for a seamless user experience.

**Comment by aryamagarwal** [comment]
Hey @LakshmiSowmya04, please list this issue under hacktoberfest and assign it to me.

**Comment by AdityaGhamat** [comment]
@LakshmiSowmya04 I am also interested for working on this problem. can you also assign me for it?

**Comment by AdityaGhamat** [comment]
@aryamagarwal Hi Arya, I’m interested in collaborating on this issue with you. Can we discuss task division and our approach for OTP implementation? Please let me know your thoughts!

**Comment by mahabubx7** [comment]
@LakshmiSowmya04 and @AdityaGhamat I would like to contribute if you have no problem with it.

I can help you to make the OTP code or passcode and SMTP email setup in this project. 
My initial idea:
```ts
// demo OTP 4 digits {string}
'2486'

// 6 digits
'385201'

// or, passcode like secret code; length >= 6
'm3K70'
``` 

It can be anything as you want or needed

**Comment by aryamagarwal** [comment]
Hi @AdityaGhamat @mahabubx7, I am interested in collaborating with you guys on this issue. Can you guys provide overview of the technical approach your are planning. This will help to have a common plan and dividing tasks will be easier.

**Comment by AdityaGhamat** [comment]
@aryamagarwal To implement OTP-based email verification, I will update the MongoDB schema by adding fields for otpCode, otpExpiry, and isVerified in the user model to track OTP status. I will create controllers to handle OTP generation, email delivery using nodemailer, and validation by comparing the stored OTP and its expiry time. Additionally, I'll add an API route for OTP verification, and include a resend functionality.this is my basic idea on going for this problem

**Comment by mahabubx7** [comment]
I would like make an update on the mongodb schema to self-destruct the document after it expires according to its expiry timestamp. Also, an util-function for generating unique OTP codes as we need.

**Comment by aryamagarwal** [comment]
LGTM @AdityaGhamat, I guess we can easily divide the work. @AdityaGhamat if you don't mind you can work on otp validation, @mahabubx7 would you mind working on unique otp generation and expiry and I can work on email delivery through node mailer. Is it fine with you guys? Ig We can continue our convo on the communication channel.
